name: Build Linux arm64 (Cross compile from x86_64.) 

on: workflow_dispatch

jobs:
  build_linux_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -lha
      - run: "echo hello world ${HOME}"
      - name: Install bootstrap dependencies.
        run: sudo apt-get update && sudo apt-get -y install debootstrap binfmt-support qemu-user-static
      - name: Set chroot path.
        run: echo "ARM64_CHROOT=${HOME}/ubuntu-22.04-arm64" >> "$GITHUB_ENV"
      - name: Make chroot path
        run: sudo mkdir "${ARM64_CHROOT}"
      - name: Bootstrap ubuntu 22.04 LTS arm64 into chroot
        run: sudo debootstrap --arch=arm64 jammy "${ARM64_CHROOT}" http://ports.ubuntu.com/ubuntu-ports
      - name: Do bind mounts
        run: bash -c "for f in dev dev/pts sys proc run ; do sudo mount --bind /$f ${ARM64_CHROOT}/$f ; done"
      - name: Launch build within chroot
        run: sudo chroot "${ARM64_CHROOT}" /bin/bash -c "uname -a"

