name: Build Linux arm64 (Cross compile from x86_64.) 

on: workflow_dispatch

jobs:
  build_linux_arm64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pwd
      - run: ls -lha
      - run: echo hello world

